-- Add extra fields to pasien table for profile & login
ALTER TABLE pasien
  ADD COLUMN IF NOT EXISTS "noBPJS" VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "golonganDarah" VARCHAR(5) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "tanggalLahir" DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS alamat TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS "jenisKelamin" VARCHAR(2) DEFAULT NULL;
